markdown: kramdown
kramdown:
  toc_levels: 2..6
title: findprob documentation
description: Rebecca Dang, Jessica Lin, Samantha Huang
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
